---

- hosts: all
  become: true
  tasks:

  # CentOS

  - name: install httpd and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
