---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
  
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBtIw63IxPWG5N/itu62i1IsZ+ppw4qkvakhxIPdhyI ANSIBLE-KEY"
    

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip 
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  # CentOS

  - name: install httpd and php packages for CentOS
    tags: apache,centos,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  # Ubuntu

  - name: install apache2 and php packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin' #used to find the staring string of the line we want to change
      line: ServerAdmin somebody@somewhere.net #change the line to what we want
    when: ansible_distribution == "CentOS"
    register: httpd #allows Ansible to capture the state of a service in a variable

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed      

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  
  # CentOS
  
  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    yum:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  # Ubuntu

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
 
- hosts: file_servers
  tags: samba
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

