- name: install httpd and php packages for CentOS
  tags: apache,centos,httpd
  yum:
   name:
    - httpd
    - php
   state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

  
  
- name: install apache2 and php packages for Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name:
     - apache2
     - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"
  
- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin' #used to find the staring string of the line we want to change
    line: ServerAdmin somebody@somewhere.net #change the line to what we want
  when: ansible_distribution == "CentOS"
  register: httpd #allows Ansible to capture the state of a service in a variable

- name: restart httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

