- name: install httpd package (CentOS)
  yum:
    name: httpd
    state: latest
  when: "'web_servers' in group_names"

- name: start and enable httpd (CentOS)
  service:
    name: httpd
    state: started
    enabled: yes

- name: copy files to webserver
  copy:
    src: /root/ansible_tasks/ansible-task3/files/worker1.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  when: "'web_servers' in group_names"

- name: change email address for admin
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: "'web_servers' in group_names"
  register: httpd

- name: restart httpd (CentOS)
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  become: yes

- name: enable port 80
  firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    state: enabled
  become: yes

- name: enable port 443
  firewalld:
    zone: public
    port: 443/tcp
    permanent: true
    state: enabled
  become: yes

- name: restart firewalld
  service:
    name: firewalld
    state: restarted


