---

- hosts: all
  become: true
  vars_files:
    - /root/ansible_tasks/ansible-task2/variables/secrets.yml

  tasks:

  - name: Create user
    user:
      name: developer
      state: present
      password: "{{ password | password_hash('sha512', 'A512') }}"
      home: /var/lib/developer
    when: "'prod' in group_names"

